### ISSUE TITLE
Embedded Lua support

### ISSUE THREAD

**Issue by myfreeweb** [chr4/nginx.vim#1]
https://github.com/hexchain/vim-openresty supports highlighting for embedded Lua code snippets… please steal that :)

(and then get into the vim-polyglot pack: sheerun/vim-polyglot/issues/187)

**Comment by chr4** [comment]
Thanks for the suggestion! I'm currently working on highlighting included `erb` and `jinja` templating, so this might be similar. 

As far as I understand the openresty plugin, some other lua-vim plugin is required to highlight lua?
Can you comment on that, and maybe paste a snipped to test lua highlighting?

I'd also apprechiate a pull-request if you find the time for either of the suggestions.

**Comment by chr4** [comment]
Done. Thanks again for the suggestion!
