### ISSUE TITLE
ssl_conf_command: add syntax highlighting

### ISSUE THREAD

**Issue by HLFH** [chr4/nginx.vim#23]
ssl_conf_command: add syntax highlighting

syntax highlighting is currently not present for this nginx directive.

**Comment by chr4** [comment]
Thanks for the report! It seems like [upstream nginx vim plugin](https://github.com/nginx/nginx/blob/master/contrib/vim/syntax/nginx.vim) has support for some more recent commands.

Unfortunately, upstream diverged quite a bit from this plugin over time - but I'd apprechiate bringing them up to date.

If you find the time to add some of the more recent commands, pull requests are welcome!

**Comment by chr4** [comment]
Closed by https://github.com/chr4/nginx.vim/pull/25
