### ISSUE TITLE
Installation should mention ~/.vim/plugin

### ISSUE THREAD

**Issue by Trahloc** [chr4/nginx.vim#4]
https://github.com/chr4/nginx.vim#installation
Anyone with a package manager for vim should know how to use their package manager.  Those not using one may never have installed a vim plugin before so the first entry listed in installation should be vim's own default location:  ~/.vim/plugins 

Thanks for making the file btw, made it really convenient to see syntax highlighting on a remote server with a minimal install.

**Comment by VadimKulagin** [comment]
I agree.
By the way, here you can see how to install the plugin manager `vim-plug`:
https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation

**Comment by chr4** [comment]
Thanks for the hint! Neovim uses `~/.config/nvim` instead as a default directory, so I tried keeping this more general. But I agree, that this might be a barrier for new users... 

Not sure howto handle this best, to be honest.

**Comment by RJanata** [comment]
Hi, I one of those linux newbies who has never used any vim's plugin manager. It took quite looong where to copy this plugin to, how to activate it and later it took me some time struggling with vim plugin manager.

To simplify this process to other new users, I've updated README.md with some extra instructions.

**Comment by chr4** [comment]
I'm sorry for the inconvenience. Thanks for taking care of it! 

Closing, as #10 hopefully fixes this.

**Comment by sskras** [comment]
@chr4 commented [on Jan 8, 2020](#issuecomment-572010294):

> Closing, as #10 hopefully fixes this.

Still open. :)
